// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL, which cannot go through the PgBouncer pooler.
    // The app itself uses the pooled DATABASE_URL — see src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
