-- The shared list of running clubs a runner picks from at sign-up, plus the
-- club recorded on each runner.
--
-- One master list across every event rather than a copy per event: the same
-- clubs turn up race after race, and a new organizer should not have to retype
-- fifty of them.

CREATE TABLE "RunningCommunity" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    -- Uppercased "name". Uniqueness lives here rather than on "name" so that
    -- "Team Army" cannot join a list that already holds "TEAM ARMY".
    "slug" TEXT NOT NULL,
    -- 'APPROVED' is suggested to runners; 'PENDING' is a write-in only the
    -- super admin has seen. New rows default to PENDING, so the seeds below
    -- set their status explicitly.
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RunningCommunity_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "RunningCommunity_slug_key" ON "RunningCommunity"("slug");

-- The pickers read approved names in alphabetical order; the super admin page
-- reads pending ones. Both are covered by this.
CREATE INDEX "RunningCommunity_status_name_idx" ON "RunningCommunity"("status", "name");

-- The club a runner represents. NOT NULL with a default so existing runners
-- stay valid without a backfill pass, and so a club tally always adds up to the
-- head count. The field is optional in the form; a blank answer is stored as
-- 'INDEPENDENT RUNNER', which is itself one of the seeded options.
ALTER TABLE "Runner" ADD COLUMN "runningCommunity" TEXT NOT NULL DEFAULT 'INDEPENDENT RUNNER';

-- The starting list, taken from the "WHICH RUNNING COMMUNITY/IES DO YOU
-- REPRESENT?" question on the Tarlac Meet and Run 2026 registration form.
-- Seeded as APPROVED: these are already in use, not write-ins awaiting review.
INSERT INTO "RunningCommunity" ("id", "name", "slug", "status", "createdAt", "updatedAt") VALUES
  ('rc_seed_001', '4-11 RUNNERS', '4-11 RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_002', 'ACA GROUP', 'ACA GROUP', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_003', 'ATHLETE X', 'ATHLETE X', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_004', 'CAFA RUNNING CLUB', 'CAFA RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_005', 'COFFEE AND MILES CLUB', 'COFFEE AND MILES CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_006', 'CONCEPCION UNITED RUNNERS', 'CONCEPCION UNITED RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_007', 'CONCEPCION RIOT', 'CONCEPCION RIOT', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_008', 'CRESENDO RUNNING COMMUNITY', 'CRESENDO RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_009', 'DEPED TARLAC RUNNING COMMUNITY', 'DEPED TARLAC RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_010', 'FIREFOX RUNNING COMMUNITY', 'FIREFOX RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_011', 'FITNESS GYM RUNNERS', 'FITNESS GYM RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_012', 'GERONA ASPIRING RUNNERS', 'GERONA ASPIRING RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_013', 'GERUNA RUNNING CLUB', 'GERUNA RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_014', 'GRASSLAND RUNNING COMMUNITY', 'GRASSLAND RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_015', 'GRIND ATHLETICS', 'GRIND ATHLETICS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_016', 'HASHEM ACADEMY INC.', 'HASHEM ACADEMY INC.', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_017', 'INDEPENDENT RUNNER', 'INDEPENDENT RUNNER', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_018', 'IRONMILER RUNNING COMMUNITY', 'IRONMILER RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_019', 'KAI''S RUNNING COMMUNITY', 'KAI''S RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_020', 'LA PAZ RUNNING COMMUNITY', 'LA PAZ RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_021', 'LUCINDA RUNNERS', 'LUCINDA RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_022', 'MALIWALO RUNNING COMMUNITY', 'MALIWALO RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_023', 'MC PARK RUNNER TEAM', 'MC PARK RUNNER TEAM', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_024', 'MODICUM TARLAC RUNNING COMMUNITY', 'MODICUM TARLAC RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_025', 'NACIA RUNNING COMMUNITY', 'NACIA RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_026', 'NCC RUNNING COMMUNITY', 'NCC RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_027', 'NUEVA ECIJA RUNNERS', 'NUEVA ECIJA RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_028', 'PAMBATO RUNNERS', 'PAMBATO RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_029', 'PANGASINAN RUN CLUB', 'PANGASINAN RUN CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_030', 'PANIQUI RUNNING CLUB', 'PANIQUI RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_031', 'PHT TARLAC', 'PHT TARLAC', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_032', 'PRC PIRIT RUNNING COMMUNITY', 'PRC PIRIT RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_033', 'RED IRON', 'RED IRON', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_034', 'ROTARUNNERS', 'ROTARUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_035', 'RUN PGT', 'RUN PGT', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_036', 'RUNNER''S HIGH', 'RUNNER''S HIGH', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_037', 'RUN TARLAC LUCINDA RUNNERS', 'RUN TARLAC LUCINDA RUNNERS', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_038', 'SAN PABLO RUNNING COMMUNITY', 'SAN PABLO RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_039', 'SAN RAFAEL RUNNING COMMUNITY', 'SAN RAFAEL RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_040', 'SAPANG MARAGUL COMMUNITY', 'SAPANG MARAGUL COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_041', 'SOLIDO RUNNING COMMUNITY', 'SOLIDO RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_042', 'SOLO RUNNING CLUB', 'SOLO RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_043', 'SOUTHWOODS RUN CLUB', 'SOUTHWOODS RUN CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_044', 'TEAM ARMY', 'TEAM ARMY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_045', 'TEAM AURUM', 'TEAM AURUM', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_046', 'TEAM TSAPSUY', 'TEAM TSAPSUY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_047', 'THE BARELY RUNNING COMMUNITY', 'THE BARELY RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_048', 'THE COMMUNITY RUNNER', 'THE COMMUNITY RUNNER', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_049', 'THE VALENTIN FAMILY RUNNING CLUB', 'THE VALENTIN FAMILY RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_050', 'TMP', 'TMP', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_051', 'TRAINING GROUND RUNNING CLUB', 'TRAINING GROUND RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_052', 'UP AND RUNNING CLUB', 'UP AND RUNNING CLUB', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rc_seed_053', 'VICTORIA RUNNING COMMUNITY', 'VICTORIA RUNNING COMMUNITY', 'APPROVED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;
